#!/bin/sh
#
# Хук срабатывает после merge, если merge выполнялся в ветке master
# 

# Версионный файл
versionFile="ERegion.Web/App_Code/AssemblyInfo.cs"

# узнаём название текущей ветки
branch="$(git symbolic-ref HEAD 2>/dev/null)" || branch="(unnamed branch)"
branch=${branch##refs/heads/}

# проверяем не в master'е ли мы
if [ "$branch" = "master" ]; then 
# увеличиваем на 1 последнее число в нужном файле и удаляем временный файл
 perl -pi.bak -e 's/(\d+)"/$1 + 1/e' $versionFile && perl -pi.bak -e 's/(\d.\d.\d.\d*)/$1"/' $versionFile
 rm "$versionFile".bak
# переписываем последний коммит
 git add $versionFile
 git commit --amend --no-edit
fi
